[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = ["NODE_ENV=development npm ci"]

[phases.build]
cmds = ["NODE_ENV=development npm run build"]

[start]
cmd = "npm run db:push && npm start"
